; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Mon Sep 16 2019 12:27:14 GMT+0200 (Central European Summer Time)
M83              ; relative extruder moves
G1 E-10 F3600    ; retract 10mm of filament
G91              ; relative positioning
G1 Z5 F360       ; lift Z by 5mm
G90              ; absolute positioning
G1 Y242 X164 F6000 ; go to X=164 Y242
