; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jun 20 2020 11:43:50 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P0 S90 ; retract BLTouch
