; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Mon Sep 16 2019 12:27:15 GMT+0200 (Central European Summer Time)

; Wait for set temperatures to be reached
M116 P0
