; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0 on Mon Jun 10 2024 15:59:00 GMT+0200 (Central European Summer Time)

; home Z
G91
var maxTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G1 H1 Z{-var.maxTravel} F600 ; coarse home in the -Z direction
G1 Z5 F6000 ; move back 5mm
G1 H1 Z{-var.maxTravel} F300 ; fine home in the -Z direction
G90