; retractprobe0.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.0 on Mon Jun 10 2024 15:59:00 GMT+0200 (Central European Summer Time)

M280 P0 S90	; retract BLTouch
